name: product_list
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  provider: ^6.1.2
  http: ^1.2.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  image: ^4.3.0
  shared_preferences: ^2.3.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/poppins/
